# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab440d6d951cc98f86567eec829689702f2dad469a2d3e1f520f1e77c24b1bbd8922418f5e12354faf18f26a3294ada0732a29106e5e2d30e1e28b202c68df5c

test:
  secret_key_base: ddf39f83f8da3065c379cc15f127d306a18b56776e7f9a278a17089a282156aa2d9a9828d043aacfed91befcbc69cc5942de5e533fc3bebe9de1fcca2ace07eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 856388738b4b6103a49f37e35fad00534bc83ccb8242f3b33489715b4b51aebb6beced42ceaebbde70e74a2599a8647007d1b7989c4fad9aa6d48f7d59f62e15
